# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2019-12-22 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import lists.models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_item_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='list',
            field=models.TextField(default='', verbose_name=lists.models.List),
        ),
    ]
